---

name: Deploy Documentation Website

on:
  push:
    branches:
      - master
    paths: 
      - docs/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        if: github.repository == 'HariboDev/aws-ec2-profiles'

      - name: Download dependencies
        if: github.repository == 'HariboDev/aws-ec2-profiles'
        run: |
          cd docs
          sudo pip3 install -U sphinx
          sudo pip3 install -r requirements.txt
          make clean
          make html

      - name: Upload docs HTML build to S3
        if: github.repository == 'HariboDev/aws-ec2-profiles'
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          SOURCE_DIR: ${{ secrets.SOURCE_DIRECTORY }}
          AWS_REGION: 'eu-west-1'
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Invalidate CloudFront Cache
        if: github.repository == 'HariboDev/aws-ec2-profiles'
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
          PATHS: '/'
          AWS_REGION: 'us-east-1'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}